AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Step Functions for Sentiment Analysis

Parameters:
  RedditScraperName:
    Type: String
    Description: Name of the Reddit scraper Lambda function
  SteamScraperName:
    Type: String
    Description: Name of the Steam scraper Lambda function
  SentimentJobCreatorName:
    Type: String
    Description: Name of the sentiment job creator Lambda function
  GetJobStatusName:
    Type: String
    Description: Name of the job status checker Lambda function
  SyncPostToSupabaseName:
    Type: String
    Description: Name of the sync post to Supabase Lambda function
  BucketName:
    Type: String
    Description: Name of the S3 bucket for storing posts
  ErrorTopicName:
    Type: String
    Description: Name of the SNS topic for error notifications
  ErrorTopicArn:
    Type: String
    Description: ARN of the SNS topic for error notifications

Resources:
  KeywordPipelineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/KeywordPipeline
      RetentionInDays: 7
      
  JobProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/JobProcessorPipeline
      RetentionInDays: 7

  # First pipeline - handles scraping and job creation
  KeywordPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt KeywordPipelineLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref RedditScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SteamScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SentimentJobCreatorName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
        - AWSStepFunctionsFullAccess
      Definition:
        StartAt: GetConfiguration
        States:
          GetConfiguration:
            Type: Task
            Resource: "arn:aws:states:::aws-sdk:s3:getObject"
            Parameters:
              Bucket: !Ref BucketName
              Key: "config/keywords_config.json"
            ResultSelector:
              Json.$: "States.StringToJson($.Body)"
            OutputPath: "$.Json"
            Next: SelectScrapers
          SelectScrapers:
            Type: Parallel
            Branches:
              - StartAt: ProcessRedditTasks
                States:
                  ProcessRedditTasks:
                    Type: Map
                    InputPath: $.source.reddit
                    MaxConcurrency: 50
                    ToleratedFailurePercentage: 40
                    Iterator:
                      ProcessorConfig:
                        Mode: DISTRIBUTED
                        ExecutionType: EXPRESS
                      StartAt: RedditScraper
                      States:
                        RedditScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref RedditScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          Next: StoreRedditPosts
                        StoreRedditPosts:
                          Type: Map
                          ItemsPath: $.posts
                          ItemSelector:
                            Key.$: States.Format('posts/{}/{}.json', $$.Map.Item.Value.execution_id, $$.Map.Item.Value.id)
                            Body.$: $$.Map.Item.Value
                          # output of the map:
                          # [{"Body": {"id": "123"}, "Key": "posts/{execution_id}/123.json"}]
                          # transform to: {"success": ["123"]}
                          ResultSelector:
                            success.$: $[*].Key
                          Iterator:
                            StartAt: StoreRedditPostToS3
                            States:
                              StoreRedditPostToS3:
                                Type: Task
                                Resource: "arn:aws:states:::aws-sdk:s3:putObject"
                                Parameters:
                                  Bucket: !Ref BucketName
                                  Key.$: $.Key
                                  Body.$: $.Body
                                  ContentType: application/json
                                ResultPath: null # don't need stored status and keep original input
                                End: true
                          End: true
                    End: true
                    Retry:
                      - ErrorEquals:
                          - States.TaskFailed
                          - States.Timeout
                        BackoffRate: 2
                        IntervalSeconds: 20
                        MaxAttempts: 3
                        JitterStrategy: FULL
                    Catch:
                      - ErrorEquals:
                          - States.TaskFailed
                          - States.Timeout
                        Next: SNSPublishRedditError
                        ResultPath: $.error
                  SNSPublishRedditError:
                    Type: Task
                    Resource: "arn:aws:states:::sns:publish"
                    Parameters:
                      TopicArn: !Ref ErrorTopicArn
                      "Message.$": "$"
                    End: true
              - StartAt: ProcessSteamTasks
                States:
                  ProcessSteamTasks:
                    Type: Map
                    InputPath: $.source.steam
                    ToleratedFailurePercentage: 30
                    MaxConcurrency: 90
                    Iterator:
                      ProcessorConfig:
                        Mode: DISTRIBUTED
                        ExecutionType: EXPRESS
                      StartAt: SteamScraper
                      States:
                        SteamScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref SteamScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          Next: StoreSteamPosts
                        StoreSteamPosts:
                          Type: Map
                          ItemsPath: "$.posts"
                          ItemSelector:
                            Key.$: States.Format('posts/{}/{}.json', $$.Map.Item.Value.execution_id, $$.Map.Item.Value.id)
                            Body.$: $$.Map.Item.Value
                          # see StoreRedditPosts for explanation
                          ResultSelector:
                            success.$: $[*].Key
                          Iterator:
                            StartAt: StoreSteamPostToS3
                            States:
                              StoreSteamPostToS3:
                                Type: Task
                                Resource: "arn:aws:states:::aws-sdk:s3:putObject"
                                Parameters:
                                  Bucket: !Ref BucketName
                                  Key.$: $.Key
                                  Body.$: $.Body
                                  ContentType: application/json
                                ResultPath: null
                                End: true
                          End: true
                    End: true
                    Retry:
                      - ErrorEquals:
                          - States.TaskFailed
                          - States.Timeout
                        BackoffRate: 2
                        IntervalSeconds: 20
                        MaxAttempts: 3
                        JitterStrategy: FULL
                    Catch:
                      - ErrorEquals:
                          - States.TaskFailed
                          - States.Timeout
                        Next: SNSPublishSteamError
                        ResultPath: $.error
                  SNSPublishSteamError:
                    Type: Task
                    Resource: "arn:aws:states:::sns:publish"
                    Parameters:
                      TopicArn: !Ref ErrorTopicArn
                      "Message.$": "$"
                    End: true
            # output of the map: 
            # (each branch returns a list object, then the map wrap it in another list)
            # note that there are error objectts mixed in, as we defined ToleratedFailurePercentage
            # [[{"success": ["key1"]}, {"error": "timeout"}], [{"success": ["key2"]}]...]
            # transform to:
            # ["key1", "key2"]
            QueryLanguage: JSONata
            Output: "{% $states.result.[*][*].'success' %}"
            # add execution id so they can be stored in s3 /{execution_id}/{post_id}.json
            Arguments:
              source:
                reddit: "{% [$map($states.input.source.reddit, function($v) { $merge([$v, { 'ephermeral_execution_id': $split($states.context.Execution.Id, ':')[-1] }]) })] %}"
                steam: "{% [$map($states.input.source.steam, function($v) { $merge([$v, { 'ephermeral_execution_id': $split($states.context.Execution.Id, ':')[-1] }]) })] %}"
            Next: CreateSentimentJob
          CreateSentimentJob:
            Type: Task
            OutputPath: $.Payload
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: !Ref SentimentJobCreatorName
              Payload.$: $
            Next: StartJobProcessor
          StartJobProcessor:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution"
            Parameters:
              StateMachineArn: !Ref JobProcessorPipeline
              Input.$: "$"
            End: true
            
      # Add the Events section directly to the StateMachine
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: "{}"  # Empty input, since we're loading from S3

  # Second pipeline - handles job processing
  JobProcessorPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt JobProcessorLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref GetJobStatusName
        - LambdaInvokePolicy:
            FunctionName: !Ref SyncPostToSupabaseName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
        - AWSStepFunctionsFullAccess
      Definition:
        StartAt: GetJobStatus
        States:
          GetJobStatus:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: !Ref GetJobStatusName
              Payload.$: "$"
            OutputPath: "$.Payload"
            Next: JobComplete
          JobComplete:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "COMPLETED"
                Next: MapPosts
              - Variable: "$.status"
                StringEquals: "FAILED"
                Next: SNSPublishError
            Default: Wait75Seconds
          Wait75Seconds:
            Type: Wait
            Seconds: 75
            Next: GetJobStatus
          MapPosts:
            Type: Map
            QueryLanguage: JSONata
            Comment: Map posts that are stored in S3
            Output: "{% $states.result.[*][*] %}"
            Items: "{% $states.input.post_keys %}"
            ItemProcessor:
              ProcessorConfig:
                Mode: DISTRIBUTED
                ExecutionType: EXPRESS
              StartAt: SyncPostToSupabase
              States:
                SyncPostToSupabase:
                  Type: Task
                  Resource: "arn:aws:states:::lambda:invoke"
                  Parameters:
                    FunctionName: !Ref SyncPostToSupabaseName
                    Payload.$: "$"
                  OutputPath: "$.Payload"
                  End: true
            Label: Map
            MaxConcurrency: 250
            ItemBatcher:
              MaxItemsPerBatch: 5
              BatchInput:
                Job: "{% $states.input %}"
            Retry:
              - ErrorEquals:
                  - States.TaskFailed
                  - States.Timeout
                BackoffRate: 2
                IntervalSeconds: 20
                MaxAttempts: 3
                JitterStrategy: FULL
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: SNSPublishError
            End: true
          SNSPublishError:
            Type: Task
            Resource: "arn:aws:states:::sns:publish"
            Parameters:
              TopicArn: !Ref ErrorTopicArn
              Message.$: "$"
            Next: FailJob
          FailJob:
            Type: Fail
            Error: "Poll job failed, check logs for more details"

Outputs:
  KeywordPipelineArn:
    Description: Step Functions ARN for the keyword pipeline
    Value: !Ref KeywordPipeline
  JobProcessorPipelineArn:
    Description: Step Functions ARN for the job processor pipeline
    Value: !Ref JobProcessorPipeline