AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Step Functions for Sentiment Analysis

Parameters:
  RedditScraperName:
    Type: String
    Description: Name of the Reddit scraper Lambda function
  SteamScraperName:
    Type: String
    Description: Name of the Steam scraper Lambda function
  SentimentJobCreatorName:
    Type: String
    Description: Name of the sentiment job creator Lambda function
  GetJobStatusName:
    Type: String
    Description: Name of the job status checker Lambda function
  SyncPostToSupabaseName:
    Type: String
    Description: Name of the sync post to Supabase Lambda function
  BucketName:
    Type: String
    Description: Name of the S3 bucket for storing posts
  ErrorTopicName:
    Type: String
    Description: Name of the SNS topic for error notifications

Resources:
  KeywordPipelineLogGroup :
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/KeywordPipeline
      RetentionInDays: 7
      
  JobProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/JobProcessorPipeline
      RetentionInDays: 7

  # First pipeline - handles scraping and job creation
  KeywordPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt KeywordPipelineLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref RedditScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SteamScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SentimentJobCreatorName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt JobProcessorPipeline.Name
      Definition:
        StartAt: SelectScrapers
        States:
          SelectScrapers:
            Type: Parallel
            Branches:
              - StartAt: ProcessRedditTasks
                States:
                  ProcessRedditTasks:
                    Type: Map
                    InputPath: $.source.reddit
                    ItemSelector:
                      Key.$: States.Format('posts/{}.json', $.id)"
                      Body.$: $$.Map.Item.Value
                    MaxConcurrency: 40
                    Iterator:
                      StartAt: RedditScraper
                      States:
                        RedditScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref RedditScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          Next: StoreRedditPosts
                        StoreRedditPosts:
                          Type: Map
                          ItemsPath: $.posts
                          MaxConcurrency: 40
                          Iterator:
                            StartAt: StoreRedditPostToS3
                            States:
                              StoreRedditPostToS3:
                                Type: Task
                                Resource: "arn:aws:states:::aws-sdk:s3:putObject"
                                Parameters:
                                  Bucket: !Ref BucketName
                                  Key.$: $.Key
                                  Body.$: $.Body
                                  ContentType: application/json
                                End: true
                          ResultPath: $.stored_posts
                          End: true
                      ProcessorConfig:
                        Mode: INLINE
                    End: true
                    OutputPath: $[*].posts[*].id
              - StartAt: ProcessSteamTasks
                States:
                  ProcessSteamTasks:
                    Type: Map
                    InputPath: $.source.steam
                    ItemSelector:
                      Key.$: States.Format('posts/{}.json', $.id)"
                      Body.$: $$.Map.Item.Value
                    MaxConcurrency: 40
                    Iterator:
                      StartAt: SteamScraper
                      States:
                        SteamScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref SteamScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          Next: StoreSteamPosts
                        StoreSteamPosts:
                          Type: Map
                          ItemsPath: "$.posts"
                          MaxConcurrency: 40
                          Iterator:
                            StartAt: StoreSteamPostToS3
                            States:
                              StoreSteamPostToS3:
                                Type: Task
                                Resource: "arn:aws:states:::aws-sdk:s3:putObject"
                                ItemSelector:
                                  Bucket: !Ref BucketName
                                  Key.$: $.Key
                                  Body.$: $.Body
                                  ContentType: application/json
                                End: true
                          ResultPath: "$.stored_posts"
                          End: true
                      ProcessorConfig:
                        Mode: INLINE
                    End: true
                    OutputPath: $[*].posts[*].id
            OutputPath: $[*][*]
            Next: CreateSentimentJob
          CreateSentimentJob:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: !Ref SentimentJobCreatorName
              Payload.$: "$"
            OutputPath: "$.Payload"
            Next: StartJobProcessor
          StartJobProcessor:
            Type: Task
            Resource: "arn:aws:states:::states:startExecution"
            Parameters:
              StateMachineArn: !Ref JobProcessorPipeline
              Input.$: "$"
            End: true
      # Add the Events section directly to the StateMachine
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: |
              {
                "source": {
                  "reddit": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "elden ring",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "cyberpunk 2077",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "the witcher 3",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "red dead redemption 2",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "gta v",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "starfield",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "hogwarts legacy",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "baldur's gate 3",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "nier automata",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "call of duty",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "fifa 24",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "apex legends",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "valorant",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "league of legends",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "fortnite",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    }
                  ],
                  "steam": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "nier automata",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "elden ring",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "cyberpunk 2077",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "the witcher 3",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "red dead redemption 2",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "gta v",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "starfield",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "hogwarts legacy",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "baldur's gate 3",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "call of duty",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "fifa 24",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "apex legends",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "valorant",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "league of legends",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "fortnite",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    }
                  ]
                }
              }

  # Second pipeline - handles job processing
  JobProcessorPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt JobProcessorLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref GetJobStatusName
        - LambdaInvokePolicy:
            FunctionName: !Ref SyncPostToSupabaseName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
        - AWSStepFunctionsFullAccess
      Definition:
        StartAt: GetJobStatus
        States:
          GetJobStatus:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: !Ref GetJobStatusName
              Payload.$: "$"
            OutputPath: "$.Payload"
            Next: JobComplete
          JobComplete:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "COMPLETED"
                Next: MapPosts
              - Variable: "$.status"
                StringEquals: "FAILED"
                Next: FailJob
            Default: Wait75Seconds
          Wait75Seconds:
            Type: Wait
            Seconds: 75
            Next: GetJobStatus
          FailJob:
            Type: Fail
            Error: "Job failed, check logs for more details"
          MapPosts:
            Type: Map
            Comment: Map posts that are stored in S3
            OutputPath: "$[*][*]"
            ItemProcessor:
              ProcessorConfig:
                Mode: DISTRIBUTED
                ExecutionType: EXPRESS
              StartAt: SyncPostToSupabase
              States:
                SyncPostToSupabase:
                  Type: Task
                  Resource: "arn:aws:states:::lambda:invoke"
                  Parameters:
                    FunctionName: !Ref SyncPostToSupabaseName
                    Payload.$: "$"
                  OutputPath: "$.Payload"
                  End: true
            Label: Map
            MaxConcurrency: 1000
            ItemBatcher:
              MaxItemsPerBatch: 5
              BatchInput:
                Job.$: "$"
            ItemReader:
              Resource: "arn:aws:states:::s3:listObjectsV2"
              Parameters:
                Bucket: !Ref BucketName
                Prefix: "posts/"
            Next: DeletePosts
          DeletePosts:
            Type: Task
            Parameters:
              Bucket: !Ref BucketName
              Delete:
                Objects.$: "$"
            Resource: "arn:aws:states:::aws-sdk:s3:deleteObjects"
            End: true

Outputs:
  KeywordPipelineArn:
    Description: Step Functions ARN for the keyword pipeline
    Value: !Ref KeywordPipeline
  JobProcessorPipelineArn:
    Description: Step Functions ARN for the job processor pipeline
    Value: !Ref JobProcessorPipeline