AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Step Functions for Sentiment Analysis

Parameters:
  RedditScraperArn:
    Type: String
  SteamScraperArn:
    Type: String
  SentimentJobCreatorArn:
    Type: String
  ErrorTopicName:
    Type: String

Resources:
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/SentimentAnalysisPipeline
      RetentionInDays: 7

  KeywordPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Logging:
        Level: ALL
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource:
                - !Ref RedditScraperArn
                - !Ref SteamScraperArn
                - !Ref SentimentJobCreatorArn
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
      Definition:
        StartAt: SelectScrapers
        States:
          SelectScrapers:
            Type: Parallel
            Branches:
              - StartAt: ProcessRedditTasks
                States:
                  ProcessRedditTasks:
                    Type: Map
                    InputPath: $.source.reddit
                    MaxConcurrency: 10
                    Iterator:
                      StartAt: RedditScraper
                      States:
                        RedditScraper:
                          Type: Task
                          Resource: !Ref RedditScraperArn
                          End: true
                    End: true
                    # FLatten [[], [], []...] to [..., ..., ...]
                    OutputPath: $[*][*]
              - StartAt: ProcessSteamTasks
                States:
                  ProcessSteamTasks:
                    Type: Map
                    InputPath: $.source.steam
                    MaxConcurrency: 10
                    Iterator:
                      StartAt: SteamScraper
                      States:
                        SteamScraper:
                          Type: Task
                          Resource: !Ref SteamScraperArn
                          End: true
                    End: true
                    # FLatten [[], [], []...] to [..., ..., ...]
                    OutputPath: $[*][*]
            OutputPath: $[*][*]
            Next: CreateSentimentJob
          CreateSentimentJob:
            Type: Task
            Resource: !Ref SentimentJobCreatorArn
            End: true
      # Add the Events section directly to the StateMachine
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: |
              {
                "source": {
                  "reddit": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    }
                  ],
                  "steam": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    }
                  ]
                }
              }

Outputs:
  StateMachineArn:
    Description: Step Functions ARN
    Value: !Ref KeywordPipeline
