AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Step Functions for Sentiment Analysis

Parameters:
  RedditScraperName:
    Type: String
    Description: Name of the Reddit scraper Lambda function
  SteamScraperName:
    Type: String
    Description: Name of the Steam scraper Lambda function
  SentimentJobCreatorName:
    Type: String
    Description: Name of the sentiment job creator Lambda function
  ErrorTopicName:
    Type: String
    Description: Name of the SNS topic for error notifications

Resources:
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/SentimentAnalysisPipeline
      RetentionInDays: 7

  KeywordPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref RedditScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SteamScraperName
        - LambdaInvokePolicy:
            FunctionName: !Ref SentimentJobCreatorName
        - SNSPublishMessagePolicy:
            TopicName: !Ref ErrorTopicName
      Definition:
        StartAt: SelectScrapers
        States:
          SelectScrapers:
            Type: Parallel
            Branches:
              - StartAt: ProcessRedditTasks
                States:
                  ProcessRedditTasks:
                    Type: Map
                    InputPath: $.source.reddit
                    MaxConcurrency: 40
                    Iterator:
                      StartAt: RedditScraper
                      States:
                        RedditScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref RedditScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          End: true
                    End: true
                    # FLatten [[], [], []...] to [..., ..., ...]
                    OutputPath: $[*][*]
              - StartAt: ProcessSteamTasks
                States:
                  ProcessSteamTasks:
                    Type: Map
                    InputPath: $.source.steam
                    MaxConcurrency: 40
                    Iterator:
                      StartAt: SteamScraper
                      States:
                        SteamScraper:
                          Type: Task
                          Resource: "arn:aws:states:::lambda:invoke"
                          Parameters:
                            FunctionName: !Ref SteamScraperName
                            Payload.$: "$"
                          OutputPath: "$.Payload"
                          End: true
                    End: true
                    # FLatten [[], [], []...] to [..., ..., ...]
                    OutputPath: $[*][*]
            OutputPath: $[*][*]
            Next: CreateSentimentJob
          CreateSentimentJob:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: !Ref SentimentJobCreatorName
              Payload.$: "$"
            OutputPath: "$.Payload"
            End: true
      # Add the Events section directly to the StateMachine
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: |
              {
                "source": {
                  "reddit": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "elden ring",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "cyberpunk 2077",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "the witcher 3",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "red dead redemption 2",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "gta v",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "starfield",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "hogwarts legacy",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "baldur's gate 3",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "nier automata",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "call of duty",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "fifa 24",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "apex legends",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "valorant",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "league of legends",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    },
                    {
                      "keyword": "fortnite",
                      "time_filter": "day",
                      "subreddits": [],
                      "sort": "top",
                      "post_limit": 6,
                      "top_comments_limit": 5
                    }
                  ],
                  "steam": [
                    {
                      "keyword": "assassin's creed",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "nier automata",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "elden ring",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "cyberpunk 2077",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "the witcher 3",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "red dead redemption 2",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "gta v",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "starfield",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "hogwarts legacy",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "baldur's gate 3",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "call of duty",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "fifa 24",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "apex legends",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "valorant",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "league of legends",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    },
                    {
                      "keyword": "fortnite",
                      "time_filter": "day",
                      "sort": "top",
                      "post_limit": 6
                    }
                  ]
                }
              }


Outputs:
  StateMachineArn:
    Description: Step Functions ARN
    Value: !Ref KeywordPipeline
