AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main template for Sentiment Analysis Pipeline

Parameters:
  RedditClientId:
    Type: String
  RedditClientSecret:
    Type: String
    NoEcho: true
  BucketName:
    Type: String
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Default: ""
  SupabaseUrl:
    Type: String
  SupabaseKey:
    Type: String
    NoEcho: true

Resources:
  # Include the infrastructure components
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure.yaml
      Parameters:
        BucketName: !Ref BucketName

  # Include the Lambda functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambdas.yaml
      Parameters:
        RedditClientId: !Ref RedditClientId
        RedditClientSecret: !Ref RedditClientSecret
        OpenAIApiKey: !Ref OpenAIApiKey
        SupabaseUrl: !Ref SupabaseUrl
        SupabaseKey: !Ref SupabaseKey
        BucketName: !Ref BucketName
        SentimentJobTableName: !GetAtt InfrastructureStack.Outputs.SentimentJobTableName

  # Include the Step Functions
  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stepfunctions.yaml
      Parameters:
        RedditScraperName: !GetAtt LambdaStack.Outputs.RedditScraperFunctionName
        SteamScraperName: !GetAtt LambdaStack.Outputs.SteamScraperFunctionName
        SentimentJobCreatorName: !GetAtt LambdaStack.Outputs.SentimentJobCreatorFunctionName
        ErrorTopicName: !GetAtt InfrastructureStack.Outputs.ErrorTopicName

Outputs:
  StateMachineArn:
    Description: Step Functions State Machine ARN
    Value: !GetAtt StepFunctionsStack.Outputs.StateMachineArn
