# cloud formation template for sentiment getter
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sentiment Analysis Pipeline for Social Media Keywords

Parameters:
  RedditClientId:
    Type: String
    Description: Reddit API Client ID
  RedditClientSecret:
    Type: String
    Description: Reddit API Client Secret
  BucketName:
    Type: String
    Description: S3 Bucket for storing results

Resources:
  # SQS Queues
  PostsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
  
  SentimentDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days

  PostsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300  # 5 minutes
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PostsDLQ.Arn
        maxReceiveCount: 3  # Move to DLQ after 3 failed attempts
      
  SentimentQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SentimentDLQ.Arn
        maxReceiveCount: 3

  # SNS Topic for Error Notifications
  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SentimentAnalysisErrors

  # Lambda Layer for Python dependencies
  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-python-deps'
      Description: Python dependencies for social media APIs (praw, tweepy)
      ContentUri: layers/python-api-packages.zip
      CompatibleRuntimes:
        - python3.11
        - python3.12
        - python3.13
      RetentionPolicy: Retain

  # Lambda Functions
  RedditScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sentiment_getter/
      Handler: functions/reddit_scraper.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          REDDIT_CLIENT_ID: !Ref RedditClientId
          REDDIT_CLIENT_SECRET: !Ref RedditClientSecret
          POSTS_QUEUE_URL: !Ref PostsQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PostsQueue.QueueName

  SentimentAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sentiment_getter/
      Handler: functions/sentiment_analyzer.lambda_handler
      Runtime: python3.12
      Timeout: 60
      Layers:
        - !Ref PythonDependenciesLayer
      Environment:
        Variables:
          SENTIMENT_QUEUE_URL: !Ref SentimentQueue
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SentimentQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PostsQueue.Arn
            BatchSize: 10

  StorageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sentiment_getter/
      Handler: functions/storage.lambda_handler
      Runtime: python3.12
      Timeout: 15
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SentimentQueue.Arn
            BatchSize: 10

  # CloudWatch Log Group for Step Functions
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/vendedlogs/states/${AWS::StackName}-KeywordPipeline'
      RetentionInDays: 7

  # Step Functions State Machine
  KeywordPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn
      Definition:
        StartAt: ProcessKeywords
        States:
          ProcessKeywords:
            Type: Map
            InputPath: "$.tasks"
            ItemProcessor:
              StartAt: ScrapeReddit
              States:
                ScrapeReddit:
                  Type: Task
                  Resource: !GetAtt RedditScraperFunction.Arn
                  Parameters:
                    "keyword.$": "$.keyword"
                    "subreddits.$": "$.subreddits"
                    "time_filter.$": "$.time_filter"
                    "sort.$": "$.sort"
                    "post_limit.$": "$.post_limit"
                  Retry:
                    - ErrorEquals: ["States.TaskFailed", "Lambda.ServiceException"]
                      IntervalSeconds: 20
                      MaxAttempts: 3
                      BackoffRate: 2.0
                  Catch:
                    - ErrorEquals: ["States.ALL"]
                      ResultPath: "$.error"
                      Next: NotifyError
                  End: true
                NotifyError:
                  Type: Task
                  Resource: "arn:aws:states:::sns:publish"
                  Parameters:
                    TopicArn: !Ref ErrorTopic
                    Message.$: "$.error"
                    Subject: "Sentiment Analysis Pipeline Error"
                  Next: FailExecution
                FailExecution:
                  Type: Fail
                  Error: "ExecutionFailed"
                  Cause: "Task execution failed, check SNS notification for details"
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RedditScraperFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ErrorTopic.TopicName
        - CloudWatchLogsFullAccess
      # https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-scheduled-rule-pattern.html
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: |
              {
                "tasks": [
                  {
                    "keyword": "league of legends",
                    "subreddits": ["all"],
                    "time_filter": "day",
                    "sort": "hot",
                    "post_limit": 10
                  },
                  {
                    "keyword": "valorant",
                    "subreddits": ["all"],
                    "time_filter": "day",
                    "sort": "hot",
                    "post_limit": 10
                  },
                  {
                    "keyword": "minecraft",
                    "subreddits": ["all"],
                    "time_filter": "day",
                    "sort": "hot",
                    "post_limit": 15
                  }
                ]
              }

  # S3 Bucket
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  StateMachineArn:
    Description: "State machine ARN"
    Value: !Ref KeywordPipeline
  ScraperFunctionArn:
    Description: "Reddit scraper function ARN"
    Value: !GetAtt RedditScraperFunction.Arn
  AnalyzerFunctionArn:
    Description: "Sentiment analyzer function ARN"
    Value: !GetAtt SentimentAnalyzerFunction.Arn
  StorageFunctionArn:
    Description: "Storage function ARN"
    Value: !GetAtt StorageFunction.Arn
  ErrorTopicArn:
    Description: "Error notification topic ARN"
    Value: !Ref ErrorTopic