AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Master template for Sentiment Analysis Pipeline

Parameters:
  RedditClientId:
    Type: String
  RedditClientSecret:
    Type: String
    NoEcho: true
  BucketName:
    Type: String
  OpenAIApiKey:
    Type: String
    NoEcho: true
  SupabaseUrl:
    Type: String
  SupabaseKey:
    Type: String
    NoEcho: true

Resources:
  # Include the infrastructure components
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure.yaml
      Parameters:
        BucketName: !Ref BucketName

  # Include the Lambda functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambdas.yaml
      Parameters:
        RedditClientId: !Ref RedditClientId
        RedditClientSecret: !Ref RedditClientSecret
        OpenAIApiKey: !Ref OpenAIApiKey
        BucketName: !Ref BucketName

  # Include the Step Functions
  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stepfunctions.yaml
      Parameters:
        RedditScraperArn: !GetAtt LambdaStack.Outputs.RedditScraperFunctionArn
        SteamScraperArn: !GetAtt LambdaStack.Outputs.SteamScraperFunctionArn
        SentimentJobCreatorArn: !GetAtt LambdaStack.Outputs.SentimentJobCreatorFunctionArn
        ErrorTopicArn: !GetAtt InfrastructureStack.Outputs.ErrorTopicArn

Outputs:
  StateMachineArn:
    Description: State machine ARN
    Value: !GetAtt StepFunctionsStack.Outputs.StateMachineArn
  ScraperFunctionArn:
    Description: Reddit scraper function ARN
    Value: !GetAtt LambdaStack.Outputs.RedditScraperFunctionArn
