AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main template for Sentiment Analysis Pipeline

Parameters:
  RedditClientId:
    Type: String
  RedditClientSecret:
    Type: String
    NoEcho: true
  BucketName:
    Type: String
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Default: ""
  SupabaseUrl:
    Type: String
  SupabaseKey:
    Type: String
    NoEcho: true
  KeywordsConfig:
    Type: String
    Description: JSON configuration for keywords to scrape
    Default: |
      {
        "source": {
          "reddit": [
            { "keyword": "assassin's creed" },
            { "keyword": "elden ring" },
            { "keyword": "cyberpunk 2077" },
            { "keyword": "the witcher 3" },
            { "keyword": "red dead redemption 2" },
            { "keyword": "gta v" },
            { "keyword": "hogwarts legacy" },
            { "keyword": "starfield" },
            { "keyword": "resident evil 4" },
            { "keyword": "baldur's gate 3" },
            { "keyword": "alan wake 2" },
            { "keyword": "lies of p" },
            { "keyword": "dead space" },
            { "keyword": "remnant ii" },
            { "keyword": "hi-fi rush" },
            { "keyword": "diablo iv" },
            { "keyword": "the callisto protocol" },
            { "keyword": "dave the diver" },
            { "keyword": "persona 5 royal" },
            { "keyword": "wo long: fallen dynasty" },
            { "keyword": "armored core vi fires of rubicon" },
            { "keyword": "sons of the forest" },
            { "keyword": "payday 3" },
            { "keyword": "ghostrunner 2" },
            { "keyword": "atomic heart" },
            { "keyword": "wild hearts" },
            { "keyword": "darkest dungeon ii" },
            { "keyword": "warhammer 40,000: darktide" },
            { "keyword": "terra nil" },
            { "keyword": "sea of stars" },
            { "keyword": "the texas chain saw massacre" },
            { "keyword": "star wars jedi: survivor" },
            { "keyword": "street fighter 6" },
            { "keyword": "tekken 8" },
            { "keyword": "nier: automata" },
            { "keyword": "nier replicant" },
            { "keyword": "mass effect legendary edition" },
            { "keyword": "forza horizon 5" },
            { "keyword": "spider-man remastered" },
            { "keyword": "spider-man miles morales" },
            { "keyword": "monster hunter rise" },
            { "keyword": "monster hunter world" },
            { "keyword": "dead island 2" },
            { "keyword": "dying light 2" },
            { "keyword": "saints row" },
            { "keyword": "far cry 6" },
            { "keyword": "rainbow six extraction" },
            { "keyword": "battlefield 2042" },
            { "keyword": "call of duty: modern warfare iii" },
            { "keyword": "control" },
            { "keyword": "quantum break" },
            { "keyword": "plague tale requiem" },
            { "keyword": "sifu" },
            { "keyword": "thymesia" },
            { "keyword": "hollow knight: silksong" },
            { "keyword": "blasphemous 2" },
            { "keyword": "stellar blade" },
            { "keyword": "doom eternal" },
            { "keyword": "resident evil village" },
            { "keyword": "frostpunk" },
            { "keyword": "shadow of the tomb raider" },
            { "keyword": "metro exodus" },
            { "keyword": "the outer worlds" },
            { "keyword": "valheim" },
            { "keyword": "no man's sky" },
            { "keyword": "hades" },
            { "keyword": "loop hero" },
            { "keyword": "factorio" },
            { "keyword": "rimworld" },
            { "keyword": "slay the spire" },
            { "keyword": "divinity: original sin 2" },
            { "keyword": "deep rock galactic" },
            { "keyword": "v rising" },
            { "keyword": "halo infinite" },
            { "keyword": "gears 5" },
            { "keyword": "god of war" },
            { "keyword": "ghost of tsushima" },
            { "keyword": "gran turismo 7" },
            { "keyword": "metroid dread" },
            { "keyword": "super mario wonder" },
            { "keyword": "the legend of zelda: tears of the kingdom" },
            { "keyword": "bayonetta 3" },
            { "keyword": "kirby and the forgotten land" },
            { "keyword": "xenoblade chronicles 3" },
            { "keyword": "fire emblem engage" },
            { "keyword": "final fantasy vii rebirth" },
            { "keyword": "death stranding" },
            { "keyword": "dragon's dogma 2" },
            { "keyword": "black myth: wukong" },
            { "keyword": "star ocean: the second story r" },
            { "keyword": "little nightmares iii" },
            { "keyword": "clock tower remaster" }
          ],
          "steam": [
            { "keyword": "assassin's creed" },
            { "keyword": "elden ring" },
            { "keyword": "cyberpunk 2077" },
            { "keyword": "the witcher 3" },
            { "keyword": "red dead redemption 2" },
            { "keyword": "gta v" },
            { "keyword": "hogwarts legacy" },
            { "keyword": "starfield" },
            { "keyword": "resident evil 4" },
            { "keyword": "baldur's gate 3" },
            { "keyword": "alan wake 2" },
            { "keyword": "lies of p" },
            { "keyword": "dead space" },
            { "keyword": "remnant ii" },
            { "keyword": "hi-fi rush" },
            { "keyword": "diablo iv" },
            { "keyword": "the callisto protocol" },
            { "keyword": "dave the diver" },
            { "keyword": "persona 5 royal" },
            { "keyword": "wo long: fallen dynasty" },
            { "keyword": "armored core vi fires of rubicon" },
            { "keyword": "sons of the forest" },
            { "keyword": "payday 3" },
            { "keyword": "ghostrunner 2" },
            { "keyword": "atomic heart" },
            { "keyword": "wild hearts" },
            { "keyword": "darkest dungeon ii" },
            { "keyword": "warhammer 40,000: darktide" },
            { "keyword": "terra nil" },
            { "keyword": "sea of stars" },
            { "keyword": "the texas chain saw massacre" },
            { "keyword": "star wars jedi: survivor" },
            { "keyword": "street fighter 6" },
            { "keyword": "tekken 8" },
            { "keyword": "nier: automata" },
            { "keyword": "nier replicant" },
            { "keyword": "mass effect legendary edition" },
            { "keyword": "forza horizon 5" },
            { "keyword": "spider-man remastered" },
            { "keyword": "spider-man miles morales" },
            { "keyword": "monster hunter rise" },
            { "keyword": "monster hunter world" },
            { "keyword": "dead island 2" },
            { "keyword": "dying light 2" },
            { "keyword": "saints row" },
            { "keyword": "far cry 6" },
            { "keyword": "battlefield 2042" },
            { "keyword": "call of duty: modern warfare iii" },
            { "keyword": "control" },
            { "keyword": "plague tale requiem" },
            { "keyword": "sifu" },
            { "keyword": "doom eternal" },
            { "keyword": "resident evil village" },
            { "keyword": "frostpunk" },
            { "keyword": "metro exodus" },
            { "keyword": "the outer worlds" },
            { "keyword": "valheim" },
            { "keyword": "black myth: wukong" },
            { "keyword": "star ocean: the second story r" },
            { "keyword": "little nightmares iii" }
          ]
        }
      }
    


Resources:
  # Include the infrastructure components
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure.yaml
      Parameters:
        BucketName: !Ref BucketName

  # Include the Lambda functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambdas.yaml
      Parameters:
        RedditClientId: !Ref RedditClientId
        RedditClientSecret: !Ref RedditClientSecret
        OpenAIApiKey: !Ref OpenAIApiKey
        SupabaseUrl: !Ref SupabaseUrl
        SupabaseKey: !Ref SupabaseKey
        BucketName: !Ref BucketName
        SentimentJobTableName: !GetAtt InfrastructureStack.Outputs.SentimentJobTableName

  # Include the Step Functions
  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stepfunctions.yaml
      Parameters:
        RedditScraperName: !GetAtt LambdaStack.Outputs.RedditScraperFunctionName
        SteamScraperName: !GetAtt LambdaStack.Outputs.SteamScraperFunctionName
        SentimentJobCreatorName: !GetAtt LambdaStack.Outputs.SentimentJobCreatorFunctionName
        GetJobStatusName: !GetAtt LambdaStack.Outputs.GetJobStatusFunctionName
        SyncPostToSupabaseName: !GetAtt LambdaStack.Outputs.SyncPostToSupabaseFunctionName
        BucketName: !Ref BucketName
        ErrorTopicName: !GetAtt InfrastructureStack.Outputs.ErrorTopicName
        ErrorTopicArn: !GetAtt InfrastructureStack.Outputs.ErrorTopicArn
        KeywordsConfig: !Ref KeywordsConfig

Outputs:
  KeywordPipelineArn:
    Description: Keyword Pipeline State Machine ARN
    Value: !GetAtt StepFunctionsStack.Outputs.KeywordPipelineArn
  JobProcessorPipelineArn:
    Description: Job Processor Pipeline State Machine ARN
    Value: !GetAtt StepFunctionsStack.Outputs.JobProcessorPipelineArn
